name: Nightly Build

on:
  push:
    branches:
      # - master
      # - main
      # - enhanced
  workflow_dispatch:

concurrency:
  group: nightly
  cancel-in-progress: true

jobs:
  check_recent_commit:
    runs-on: ubuntu-latest
    name: Check Recent Commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
      - id: should_run
        name: Check if latest commit date is within the previous 24 hours
        run: |
          if [ -z "$(git rev-list --since="24 hours ago" --all)" ]; then
            echo "should_run=false" >> $GITHUB_OUTPUT
          else
            echo "should_run=true" >> $GITHUB_OUTPUT
          fi

  build_nightly:
    runs-on: windows-latest
    name: Build Nightly
    needs: check_recent_commit
    if: needs.check_recent_commit.outputs.should_run == 'true'
    outputs:
      full_sha: ${{ steps.var.outputs.full_sha }}
      short_sha: ${{ steps.var.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Generate CMake project
        run: cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=RelWithDebInfo -S . -B build -G Ninja

      - name: Build 64bit RelWithDebInfo DLL
        run: cmake --build ./build --config RelWithDebInfo --target YimMenuV2

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: |
            build/YimMenuV2.dll
            build/YimMenuV2.pdb

      - name: Generate Build Info
        id: var
        run: |
          echo "full_sha=$(git rev-parse HEAD)" >> $env:GITHUB_OUTPUT
          echo "short_sha=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT

  recreate_release:
    runs-on: ubuntu-latest
    name: Recreate Release
    needs: build_nightly
    if: needs.check_recent_commit.outputs.should_run == 'true'
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Git Identity
        run: |
          git config --global user.name "ra1nyxin"
          git config --global user.email "ra1nyxin@users.noreply.github.com"

      - name: Delete Existing Release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const tag = "nightly";
            try {
              const { data: release } = await github.rest.repos.getReleaseByTag({ owner, repo, tag });
              await github.rest.repos.deleteRelease({ owner, repo, release_id: release.id });
              await github.rest.git.deleteRef({ owner, repo, ref: `tags/${tag}` });
            } catch (e) {
              console.log("No release/tag found to delete.");
            }

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: binary

      - name: Nightly Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          name: Nightly [${{ needs.build_nightly.outputs.short_sha }}]
          tag_name: nightly
          body: |
            ### YimMenuV2 Nightly Build
            - **Commit**: [${{ needs.build_nightly.outputs.short_sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ needs.build_nightly.outputs.full_sha }})
            - **Build Log**: [Actions Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            
            This is an automated build for personal and close-circle testing.
          files: |
            YimMenuV2.dll
            YimMenuV2.pdb
